[workspace]

members = ["*", "openapi-experiments/openapiv3", "openapi-experiments/sbi5g/temp"]
exclude  = ["rust-mrtdump", "target", ".git", "notes", "hello_world", "trait-any", "openapi-experiments", "blog_os", "serde-experiments"]
